CREATE DATABASE HELLO17;
USE HELLO17;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    EMP_NAME VARCHAR(10),
    EMP_SALARY INT
);

INSERT INTO EMPLOYEES VALUES (101,"A",10000);
SELECT * FROM EMPLOYEES;

CREATE TABLE DEPARTMENTS(
	DEPT_ID INT,
    DEPT_NAME VARCHAR(20)
);
CREATE TABLE EMPLOYES(
	EMP_ID INT,
    EMP_NAME VARCHAR(20),
    EMAIL VARCHAR(25),
    DEPT_ID INT
);

DESCRIBE DEPARTMENTS;
DESCRIBE EMPLOYES;

ALTER TABLE DEPARTMENTS
ADD PRIMARY KEY (DEPT_ID);

ALTER TABLE EMPLOYES
ADD PRIMARY KEY (EMP_ID);

ALTER TABLE EMPLOYES
ADD UNIQUE (EMAIL);

DESCRIBE EMPLOYES;

ALTER TABLE EMPLOYES
ADD CONSTRAINT FK_DEPT_ID
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID);

DESCRIBE EMPLOYES;

ALTER TABLE EMPLOYES
DROP FOREIGN KEY FK_DEPT_ID;

DESCRIBE EMPLOYES;

INSERT INTO EMPLOYES VALUES (102,"DASF","SADFADS",304);

ALTER TABLE DEPARTMENTS
DROP PRIMARY KEY;

DESCRIBE DEPARTMENTS;