CREATE DATABASE HELLO7;
USE HELLO7;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    EMP_NAME VARCHAR(50),
    SALARY DECIMAL(10,2),
    JOINING_DATE DATE
);

CREATE TABLE PRODUCTS(
	PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(100),
    PRICE FLOAT,
    MANFACTURING_DATE TIMESTAMP
);
INSERT INTO PRODUCTS VALUES (101,"P1",10.45,"2024-08-23 10:10:10");

CREATE TABLE STUDENTS(
	STUDENT_ID SMALLINT,
    STUDENT_NAME VARCHAR(50),
    AGE TINYINT,
    HEIGHT FLOAT
);

CREATE TABLE ARTICLES(
	ARTICLE_ID INT,
    TITLE VARCHAR(200),
    CONTENT TEXT
);
SELECT * FROM ARTICLES;

CREATE TABLE EMPLOYEES1(
    EMP_ID INT,
    EMP_NAME VARCHAR(50),
    GENDER ENUM("MALE","FEMALE","OTHER"),
    JOB_ROLE ENUM("DEVELOPER","MANAGE","TESTER")
);


CREATE TABLE STUDENTS1(
	STUDENT_ID INT,
    STUDENT_NAME VARCHAR(50),
    HOBBIES SET("READING","MUSIC","SPORTS","TRAVELLING")
);

CREATE TABLE PRODUCTS1(
	PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(50),
    COLOR ENUM("RED","BLUE","GREEN","BLACK","WHITE")
);
	