CREATE DATABASE HELLO14;
USE HELLO14;

CREATE TABLE EMPLOYEES1(
	EMP_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(10)
);
INSERT INTO EMPLOYEES1 VALUES (101,"A1","B1");
SELECT * FROM EMPLOYEES1;
INSERT INTO EMPLOYEES1 VALUES (102,"A2","B2");
SELECT * FROM EMPLOYEES1;
INSERT INTO EMPLOYEES1 VALUES (101,"A3","B3");
SELECT * FROM EMPLOYEES1;
INSERT INTO EMPLOYEES1 (FIRST_NAME,LAST_NAME) VALUES ("A3","B3");


CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY,
    USERNAME VARCHAR(10) UNIQUE,
    EMAIL VARCHAR(20)
);
INSERT INTO USERS VALUES (101,"A1","A1@GMAIL.COM");
SELECT * FROM USERS;
INSERT INTO USERS VALUES (102,"A2","A2@GMAIL.COM");
SELECT * FROM USERS;
INSERT INTO USERS VALUES (103,"A2","A3@GMAIL.COM");
SELECT * FROM USERS;
INSERT INTO USERS (USERNAME,EMAIL) VALUES ("A4","A4@GMAIL.COM");
INSERT INTO USERS (USER_ID,EMAIL) VALUE (104,"A5@GMAIL.COM");
SELECT * FROM USERS;

CREATE TABLE PRODUCTS(
	PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(10) NOT NULL,
    PRICE INT
);
INSERT INTO PRODUCTS VALUES (101,"P1",100);
SELECT * FROM PRODUCTS;
INSERT INTO PRODUCTS VALUES (102,"P2",200);
SELECT * FROM PRODUCTS;
INSERT INTO PRODUCTS VALUES (103,"P1",100);
SELECT * FROM PRODUCTS;
INSERT INTO PRODUCTS (PRODUCT_ID,PRICE) VALUES (104,500);

CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
    STATUS VARCHAR(10) DEFAULT "PENDING"
);
INSERT INTO ORDERS VALUE (101,"O1");
SELECT * FROM ORDERS;
INSERT INTO ORDERS VALUE (102,"SHIPPED");
SELECT * FROM ORDERS;
INSERT INTO ORDERS (ORDER_ID) VALUES (103);
SELECT * FROM ORDERS;

CREATE TABLE EMPLOYEES2(
	EMP_ID INT PRIMARY KEY,
    AGE INT CHECK (AGE >= 18),
    SALARY INT
);
INSERT INTO EMPLOYEES2 VALUES (101,21,20000);
SELECT * FROM EMPLOYEES2;
INSERT INTO EMPLOYEES2 VALUES (102,18,20000);
SELECT * FROM EMPLOYEES2;
INSERT INTO EMPLOYEES2 VALUES (103,12,12000);
SELECT * FROM EMPLOYEES2;

CREATE TABLE EMPLOYEES3(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_NAME VARCHAR(10) NOT NULL,
    SALARY INT
);
INSERT INTO EMPLOYEES3 (EMP_NAME,SALARY) VALUES ("E1",40000);
SELECT * FROM EMPLOYEES3;
INSERT INTO EMPLOYEES3 (EMP_NAME,SALARY) VALUES ("E2",50000);
SELECT * FROM EMPLOYEES3;
INSERT INTO EMPLOYEES3 VALUES (101,"E3",50000);
SELECT * FROM EMPLOYEES3;
INSERT INTO EMPLOYEES3 (EMP_NAME,SALARY) VALUES ("E3",50000);
SELECT * FROM EMPLOYEES3;