CREATE DATABASE HELLO18;
USE HELLO18;

CREATE TABLE TABLE1(
	COL1 INT PRIMARY KEY AUTO_INCREMENT,
    COL2 VARCHAR(20)
);

CREATE USER "MANAGER1" IDENTIFIED BY "1234";
GRANT ALL PRIVILEGES ON TABLE1 TO "MANAGER1";
GRANT INSERT ON TABLE1 TO "MANAGER1";
GRANT SELECT ON TABLE1 TO "MANAGER1";

REVOKE INSERT ON TABLE1 FROM "MANAGER1";

SELECT * FROM TABLE1;





