CREATE DATABASE HELLO9;
USE HELLO9;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    EMP_NAME VARCHAR(30),
    EMP_AGE TINYINT,
    EMP_SALARY DECIMAL(7,2)
);

INSERT INTO EMPLOYEES VALUES (101,"E1",45,45000);
SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES VALUES (60000,"E2",103,23);
SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES (EMP_SALARY,EMP_NAME,EMP_ID,EMP_AGE) VALUES (60000,"E2",103,23);
SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES (EMP_ID,EMP_NAME) VALUES (103,"E3");
SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES (EMP_NAME,EMP_ID) VALUES ("E5",105);
SELECT * FROM EMPLOYEES;

INSERT INTO EMPLOYEES VALUES (106,"E6",36,36000),(107,"E7",37,37000),(108,"E8",38,38000);
SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES (EMP_ID,EMP_NAME) VALUES (109,"E9"),(110,"E10"),(111,"E11");
SELECT * FROM EMPLOYEES;

CREATE TABLE NEW_EMPLOYEES1(
	EMP_ID INT,
    EMP_NAME VARCHAR(20),
    EMP_AGE TINYINT,
    EMP_SALARY DECIMAL(7,2)
);
SELECT * FROM NEW_EMPLOYEES1;
SELECT * FROM EMPLOYEES;

INSERT INTO NEW_EMPLOYEES1 (EMP_ID,EMP_NAME,EMP_AGE,EMP_SALARY)
SELECT EMP_ID,EMP_NAME,EMP_AGE,EMP_SALARY FROM EMPLOYEES;

SELECT * FROM NEW_EMPLOYEES1;

CREATE TABLE NEW_EMPLOYEES2(
	EMP_ID INT,
    EMP_NAME VARCHAR(20),
    EMP_AGE TINYINT,
    EMP_SALARY DECIMAL(7,2)
);
INSERT INTO NEW_EMPLOYEES2 (EMP_ID,EMP_NAME)
SELECT EMP_ID,EMP_NAME FROM EMPLOYEES;

SELECT * FROM NEW_EMPLOYEES2;

CREATE TABLE NEW_EMPLOYEES3(
	EMP_ID INT,
    EMP_NAME VARCHAR(20)
);
INSERT INTO NEW_EMPLOYEES3 (EMP_ID,EMP_NAME)
SELECT EMP_ID,EMP_NAME FROM EMPLOYEES;


SELECT * FROM EMPLOYEES;

SELECT * FROM NEW_EMPLOYEES1;

SET SQL_SAFE_UPDATES = 0;

DELETE FROM NEW_EMPLOYEES1 WHERE EMP_ID = 103;
SELECT * FROM NEW_EMPLOYEES1;
DELETE FROM NEW_EMPLOYEES1;
SELECT * FROM NEW_EMPLOYEES1;
SELECT * FROM NEW_EMPLOYEES2;
TRUNCATE TABLE NEW_EMPLOYEES2;
SELECT * FROM NEW_EMPLOYEES2;
SELECT * FROM NEW_EMPLOYEES3;
DROP TABLE NEW_EMPLOYEES3;
SELECT * FROM NEW_EMPLOYEES3;
SELECT * FROM EMPLOYEES;
UPDATE EMPLOYEES SET EMP_SALARY = 20000;
SELECT * FROM EMPLOYEES;
UPDATE EMPLOYEES SET EMP_AGE = 101 WHERE EMP_NAME = "E10";
SELECT * FROM EMPLOYEES;
UPDATE EMPLOYEES SET EMP_AGE = 20 WHERE EMP_AGE IS NULL;
SELECT * FROM EMPLOYEES;