CREATE DATABASE HELLO21;
USE HELLO21;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    NAME VARCHAR(20),
    DEPARTMENT VARCHAR(15),
    SALARY INT,
    AGE INT,
    CITY VARCHAR(10)
);
INSERT INTO employees VALUES
(1, 'Alice',   'HR',        40000, 28, 'Delhi'),
(2, 'Bob',     'IT',        60000, 32, 'Mumbai'),
(3, 'Charlie', 'Finance',   55000, 29, 'Bangalore'),
(4, 'Diana',   'IT',        62000, 35, 'Mumbai'),
(5, 'Eve',     'HR',        42000, 26, 'Chennai'),
(6, 'Frank',   'Finance',   53000, 31, 'Delhi'),
(7, 'Grace',   'IT',        58000, 30, 'Hyderabad');
SELECT * FROM EMPLOYEES;

SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT NAME,
	(SELECT AVG(SALARY) FROM EMPLOYEES) AS AVG_SALARY
FROM EMPLOYEES;

SELECT NAME,SALARY,
	(SELECT MAX(SALARY) FROM EMPLOYEES) - SALARY AS DIFF_SALARY
FROM EMPLOYEES;

SELECT NAME,SALARY,
	SALARY - (SELECT AVG(SALARY) FROM EMPLOYEES) AS AVG_SALARY
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT AVG(AGE) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE AGE > (SELECT AVG(AGE) FROM EMPLOYEES);


SELECT * FROM EMPLOYEES
WHERE SALARY > (
			SELECT MIN(SALARY) FROM EMPLOYEES
			WHERE DEPARTMENT = "FINANCE");
    
SELECT * FROM EMPLOYEES
WHERE CITY = (
SELECT CITY FROM EMPLOYEES
WHERE EMP_ID = 1);

SELECT * FROM EMPLOYEES
WHERE AGE < (
SELECT MAX(AGE) FROM EMPLOYEES
WHERE DEPARTMENT = "IT");

SELECT * FROM EMPLOYEES E
WHERE (
	SELECT AVG(SALARY) FROM EMPLOYEES
    WHERE DEPARTMENT = E.DEPARTMENT
) > 
(SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT AVG(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "HR";
SELECT * FROM EMPLOYYES;

SELECT * FROM EMPLOYEES
WHERE SALARY > (
SELECT SALARY FROM EMPLOYEES
WHERE NAME = "EVE");

-- SINGLE ROW SUB QUERY

SELECT * FROM EMPLOYEES
WHERE SALARY > (
SELECT AVG(SALARY) FROM EMPLOYEES
);

SELECT * FROM EMPLOYEES
WHERE CITY = (
SELECT CITY FROM EMPLOYEES WHERE EMP_ID = 5
);

SELECT * FROM EMPLOYEES
WHERE AGE > (
	SELECT MIN(AGE) FROM EMPLOYEES
    WHERE DEPARTMENT = "FINANCE"
);

SELECT * FROM EMPLOYEES
WHERE SALARY = (
	SELECT MAX(SALARY) FROM EMPLOYEES
    WHERE DEPARTMENT = "HR"
);

SELECT * FROM EMPLOYEES
WHERE SALARY < (
	SELECT SALARY FROM EMPLOYEES
    WHERE NAME = "DIANA"
);