CREATE DATABASE HELLO13;
USE HELLO13;
CREATE TABLE STUDENTS(
	STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(20),
    STUDENT_EMAIL VARCHAR(30)
);
CREATE TABLE ENROLLMENTS(
	ENROLLMENT_ID INT PRIMARY KEY,
	STUDENT_ID INT,
    COURSE_NAME VARCHAR(10),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);

INSERT INTO ENROLLMENTS VALUES (201,101,"PFS");
INSERT INTO STUDENTS VALUES (101,"S1","S1@GMAIL.COM");
INSERT INTO STUDENTS VALUES (102,"S2","S2@GMAIL.COM");
SELECT * FROM STUDENTS;
SELECT * FROM ENROLLMENTS;
INSERT INTO ENROLLMENTS VALUES (202,101,"JFS");
DELETE FROM STUDENTS WHERE STUDENT_ID = 102;
DELETE FROM STUDENTS WHERE STUDENT_ID = 101;
TRUNCATE TABLE ENROLLMENTS;

CREATE TABLE DEPARTMENTS(
	DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(20)
);
CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20),
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
);




