CREATE DATABASE HELLO20;
USE HELLO20;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(15),
    SALARY INT,
    AGE INT,
    GENDER ENUM("MALE","FEMALE","OTHERS")
);
INSERT INTO employees (emp_id, name, department, salary, age, gender) VALUES
(1, 'Alice',  'HR',    50000, 28, 'FEMALE'),
(2, 'Bob',    'IT',    70000, 32, 'MALE'),
(3, 'Carol',  'IT',    72000, 30, 'FEMALE'),
(4, 'David',  'HR',    52000, 45, 'MALE'),
(5, 'Eva',    'Sales', 60000, 29, 'FEMALE'),
(6, 'Frank',  'Sales', 58000, 35, 'MALE');

SELECT * FROM EMPLOYEES;

SELECT SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES;
SELECT SUM(SALARY) AS TOTAL_FEMALE_SALARY
FROM EMPLOYEES WHERE GENDER = "FEMALE";
SELECT SUM(SALARY) FROM EMPLOYEES
WHERE AGE < 35;
SELECT SUM(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "IT"; 


SELECT COUNT(*) FROM EMPLOYEES;
SELECT COUNT(*) FROM EMPLOYEES 
WHERE DEPARTMENT = "SALES";
SELECT COUNT(*) FROM EMPLOYEES 
WHERE SALARY > 60000;
SELECT COUNT(*) FROM EMPLOYEES 
WHERE AGE > 30 AND GENDER="MALE";

SELECT MIN(SALARY) FROM EMPLOYEES;
SELECT MIN(AGE) FROM EMPLOYEES 
WHERE GENDER = "FEMALE";
SELECT MIN(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "IT";
SELECT MIN(AGE) FROM EMPLOYEES
WHERE SALARY > 60000;

SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT MAX(AGE) FROM EMPLOYEES 
WHERE DEPARTMENT = "SALES";
SELECT MAX(SALARY) FROM EMPLOYEES 
WHERE GENDER = "MALE";
SELECT MAX(SALARY) FROM EMPLOYEES
WHERE AGE < 35;

SELECT AVG(SALARY) FROM EMPLOYEES;
SELECT AVG(AGE) FROM EMPLOYEES
WHERE AGE > 30;
SELECT AVG(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "HR";
SELECT AVG(SALARY) FROM EMPLOYEES
WHERE GENDER = "FEMALE";

SELECT * FROM EMPLOYEES;


CREATE TABLE ORDERS(
	ORDER_ID INT,
    CUSTOMER_NAME VARCHAR(20),
    PRODUCT VARCHAR(20),
    QUANTITY INT,
    PRICE INT,
    CITY VARCHAR(10)
);
INSERT INTO orders (order_id, customer_name, product, quantity, price, city) VALUES
(1, 'John',   'Laptop',     1, 75000, 'Mumbai'),
(2, 'Alice',  'Smartphone', 2, 30000, 'Delhi'),
(3, 'Bob',    'Laptop',     1, 74000, 'Bangalore'),
(4, 'Diana',  'Tablet',     3, 25000, 'Mumbai'),
(5, 'Chris',  'Smartphone', 1, 31000, 'Chennai'),
(6, 'Eva',    'Laptop',     2, 76000, 'Delhi'),
(7, 'Frank',  'Tablet',     1, 26000, 'Mumbai');
SELECT * FROM ORDERS;

SELECT PRODUCT,SUM(QUANTITY) FROM ORDERS
GROUP BY PRODUCT;
SELECT CITY,COUNT(*) FROM ORDERS
GROUP BY CITY;
SELECT PRODUCT,MIN(PRICE) FROM ORDERS
GROUP BY PRODUCT;
SELECT PRODUCT,MAX(PRICE) FROM ORDERS
GROUP BY PRODUCT;
SELECT PRODUCT,AVG(PRICE) FROM ORDERS
GROUP BY PRODUCT;
SELECT PRODUCT,SUM(QUANTITY*PRICE) FROM ORDERS
GROUP BY PRODUCT;
SELECT CITY,SUM(QUANTITY * PRICE) FROM ORDERS
GROUP BY CITY;
SELECT CITY,SUM(QUANTITY) FROM ORDERS
WHERE PRODUCT = "LAPTOP"
GROUP BY CITY;
SELECT PRODUCT,AVG(QUANTITY) FROM ORDERS
GROUP BY PRODUCT;



