CREATE DATABASE HELLO23;
USE HELLO23;

CREATE TABLE SALES(
	SALE_ID INT PRIMARY KEY,
    PRODUCT VARCHAR(20) NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    UNITS_SOLD INT,
    UNIT_PRICE INT,
    REGION VARCHAR(10)
);
INSERT INTO sales (sale_id, product, category, units_sold, unit_price, region) VALUES
(1, 'Keyboard',    'Electronics', 10, 1200,  'North'),
(2, 'Monitor',     'Electronics', 5,  7000,  'South'),
(3, 'Chair',       'Furniture',   15, 2500,  'North'),
(4, 'Desk',        'Furniture',   7,  4500,  'West'),
(5, 'Mouse',       'Electronics', 20, 800,   'East'),
(6, 'Sofa',        'Furniture',   3,  15000, 'South'),
(7, 'Headphones',  'Electronics', 8,  1800,  'North');
SELECT * FROM SALES;

-- GROUPBY + HAVING

SELECT CATEGORY,SUM(UNITS_SOLD)
FROM SALES
GROUP BY CATEGORY
HAVING SUM(UNITS_SOLD) > 25;


SELECT REGION,SUM(UNITS_SOLD * UNIT_PRICE) AS REVENUE
FROM SALES
GROUP BY REGION
HAVING REVENUE > 50000;

SELECT CATEGORY,COUNT(*) AS COUNT_OF_PRODUCTS
FROM SALES
GROUP BY CATEGORY
HAVING COUNT_OF_PRODUCTS > 3;

SELECT CATEGORY,AVG(UNIT_PRICE)
FROM SALES
GROUP BY CATEGORY
HAVING AVG(UNIT_PRICE) < 5000;


SELECT REGION,COUNT(*)
FROM SALES
WHERE CATEGORY = "ELECTRONICS"
GROUP BY REGION
HAVING COUNT(*) > 1;

-- GROUPBY + ORDER BY

SELECT CATEGORY,SUM(UNITS_SOLD)
FROM SALES
GROUP BY CATEGORY
ORDER BY SUM(UNITS_SOLD) ASC;

SELECT REGION,AVG(UNIT_PRICE)
FROM SALES
GROUP BY REGION
ORDER BY REGION ASC;

SELECT CATEGORY,SUM(UNITS_SOLD * UNIT_PRICE)
FROM SALES
GROUP BY CATEGORY
ORDER BY SUM(UNITS_SOLD * UNIT_PRICE) DESC;


SELECT REGION,COUNT(*)
FROM SALES
GROUP BY REGION
ORDER BY COUNT(*) DESC;

SELECT REGION,SUM(UNITS_SOLD)
FROM SALES
GROUP BY REGION
ORDER BY REGION;

-- GROUPBY + HAVING + ORDER BY

SELECT REGION,SUM(UNITS_SOLD * UNIT_PRICE) AS REVENUE
FROM SALES
GROUP BY REGION
HAVING REVENUE > 20000
ORDER BY REVENUE DESC;

SELECT CATEGORY,SUM(UNITS_SOLD)
FROM SALES
GROUP BY CATEGORY
HAVING SUM(UNITS_SOLD) > 10
ORDER BY CATEGORY;

SELECT REGION,COUNT(PRODUCT)
FROM SALES
GROUP BY REGION
HAVING COUNT(PRODUCT) > 1
ORDER BY REGION;

SELECT CATEGORY,AVG(UNIT_PRICE)
FROM SALES
GROUP BY CATEGORY
HAVING AVG(UNIT_PRICE) > 6000
ORDER BY AVG(UNIT_PRICE);

SELECT CATEGORY,AVG(UNITS_SOLD)
FROM SALES
GROUP BY CATEGORY
HAVING AVG(UNITS_SOLD) > 5
ORDER BY AVG(UNITS_SOLD) DESC;

