CREATE DATABASE HELLO22;
USE HELLO22;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    NAME VARCHAR(20),
    DEPARTMENT VARCHAR(15),
    SALARY INT,
    AGE INT,
    CITY VARCHAR(10)
);
INSERT INTO employees VALUES
(1, 'Alice',   'HR',        40000, 28, 'Delhi'),
(2, 'Bob',     'IT',        60000, 32, 'Mumbai'),
(3, 'Charlie', 'Finance',   55000, 29, 'Bangalore'),
(4, 'Diana',   'IT',        62000, 35, 'Mumbai'),
(5, 'Eve',     'HR',        42000, 26, 'Chennai'),
(6, 'Frank',   'Finance',   53000, 31, 'Delhi'),
(7, 'Grace',   'IT',        58000, 30, 'Hyderabad');
SELECT * FROM EMPLOYEES;

SELECT * FROM  EMPLOYEES
WHERE DEPARTMENT = (
	SELECT DEPARTMENT FROM EMPLOYEES WHERE NAME = "CHARLIE"
);
SELECT DEPARTMENT FROM EMPLOYEES WHERE NAME = "CHARLIE";

SELECT * FROM EMPLOYEES WHERE CITY = (
	SELECT CITY FROM EMPLOYEES WHERE SALARY = (
		SELECT MIN(SALARY) FROM EMPLOYEES
	)
);

SELECT * FROM EMPLOYEES 
WHERE AGE > (
	SELECT AVG(AGE) FROM EMPLOYEES WHERE DEPARTMENT = "IT"
);
SELECT AVG(AGE) FROM EMPLOYEES WHERE DEPARTMENT = "IT";

SELECT * FROM EMPLOYEES
WHERE SALARY = (
	SELECT MIN(SALARY) FROM EMPLOYEES
);
SELECT MIN(SALARY) FROM EMPLOYEES;
SELECT * FROM EMPLOYEES
WHERE AGE = (
	SELECT MAX(AGE) FROM EMPLOYEES
);
SELECT MAX(AGE) FROM EMPLOYEES;


-- MULTI ROW
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN (
	SELECT DEPARTMENT FROM EMPLOYEES
	WHERE CITY = "DELHI"
);
SELECT DEPARTMENT FROM EMPLOYEES
WHERE CITY = "DELHI";

SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT = "HR";

SELECT * FROM EMPLOYEES
WHERE SALARY IN (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);

SELECT CITY FROM EMPLOYEES
WHERE DEPARTMENT = "IT";

SELECT * FROM EMPLOYEES
WHERE CITY IN (
	SELECT CITY FROM EMPLOYEES
	WHERE DEPARTMENT = "IT"
);


SELECT * FROM EMPLOYEES
WHERE SALARY > ANY (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);

SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT = "HR";

SELECT * FROM EMPLOYEES
WHERE SALARY < ANY (
	SELECT SALARY FROM EMPLOYEES
	WHERE CITY = "MUMBAI"
);
SELECT SALARY FROM EMPLOYEES
WHERE CITY = "MUMBAI";

SELECT * FROM EMPLOYEES
WHERE SALARY > ALL (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);

SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT = "HR";

SELECT * FROM EMPLOYEES
WHERE AGE < ALL (
	SELECT AGE FROM EMPLOYEES
	WHERE DEPARTMENT = "IT"
);

SELECT AGE FROM EMPLOYEES
WHERE DEPARTMENT = "IT";

SELECT * FROM EMPLOYEES
WHERE SALARY < ALL (
	SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT = "FINANCE"
);

SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT = "FINANCE";


SELECT AVG(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "IT";
SELECT AVG(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "HR";
SELECT AVG(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "IT";
SELECT AVG(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "FINANCE";


SELECT * FROM EMPLOYEES E1
WHERE SALARY > (
	SELECT AVG(SALARY) FROM EMPLOYEES E2
    WHERE E2.DEPARTMENT = E1.DEPARTMENT
);

SELECT AVG(SALARY) FROM EMPLOYEES E2
WHERE E2.DEPARTMENT = "IT";


SELECT * FROM EMPLOYEES E1
WHERE AGE > (
	SELECT AVG(AGE) FROM EMPLOYEES E2
    WHERE E2.CITY = E1.CITY
);

SELECT * FROM EMPLOYEES E1
WHERE SALARY = (
	SELECT MAX(SALARY) FROM EMPLOYEES E2
    WHERE E1.DEPARTMENT = E2.DEPARTMENT
);

SELECT * FROM EMPLOYEES E1
WHERE AGE = (
	SELECT MIN(AGE) FROM EMPLOYEES E2
    WHERE E2.DEPARTMENT = E1.DEPARTMENT
);

SELECT * FROM EMPLOYEES E1
WHERE SALARY < ALL (
	SELECT SALARY FROM EMPLOYEES E2
    WHERE E1.CITY = E2.CITY AND E1.EMP_ID != E2.EMP_ID
);