CREATE DATABASE HELLO24;
USE HELLO24;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    DEPARTMENT VARCHAr(15) NOT NULL,
    SALARY INT,
    AGE INT,
    CITY VARCHAR(10)
);
INSERT INTO employees (emp_id, name, department, salary, age, city) VALUES
(1, 'Alice',   'HR',        40000, 28, 'Delhi'),
(2, 'Bob',     'IT',        60000, 32, 'Mumbai'),
(3, 'Charlie', 'Finance',   55000, 29, 'Bangalore'),
(4, 'Diana',   'IT',        62000, 35, 'Mumbai'),
(5, 'Eve',     'HR',        42000, 26, 'Chennai'),
(6, 'Frank',   'Finance',   53000, 31, 'Delhi'),
(7, 'Grace',   'IT',        58000, 30, 'Hyderabad');
SELECT * FROM EMPLOYEES;

SELECT DEPARTMENT,AVG(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT 
ORDER BY AVG(SALARY) DESC
LIMIT 1 ;
    
SELECT DEPARTMENT FROM (
	SELECT DEPARTMENT,AVG(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT 
	ORDER BY AVG(SALARY) DESC
	LIMIT 1 
) AS AVG_SALARIES;

SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING SUM(SALARY) > (
	SELECT SUM(SALARY) FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);

SELECT SUM(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "HR";

SELECT DEPARTMENT,AVG(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > (
	SELECT AVG(SALARY) FROM EMPLOYEES
);

SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT DEPARTMENT,COUNT(*) FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*) > (
	SELECT AVG(DEPT_COUNT) FROM (
		SELECT DEPARTMENT,COUNT(*) AS DEPT_COUNT FROM EMPLOYEES
		GROUP BY DEPARTMENT
	) AS TB1
);


SELECT AVG(DEPT_COUNT) FROM (
	SELECT DEPARTMENT,COUNT(*) AS DEPT_COUNT FROM EMPLOYEES
    GROUP BY DEPARTMENT
) AS TB1;

SELECT DEPARTMENT,COUNT(*) AS DEPT_COUNT FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING SUM(SALARY) > (
	SELECT MIN(TOTAL_SALARY) FROM (
		SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES
		GROUP BY DEPARTMENT
	) AS TB1
);

SELECT MIN(TOTAL_SALARY) FROM (
	SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES
	GROUP BY DEPARTMENT
) AS TB1;

SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(AGE) > (
	SELECT AVG(AGE) FROM EMPLOYEES
);

SELECT AVG(AGE) FROM EMPLOYEES;

SELECT CITY,SUM(SALARY) FROM EMPLOYEES
GROUP BY CITY 
HAVING SUM(SALARY) > (
	SELECT SUM(SALARY) FROM EMPLOYEES
	WHERE CITY = "DELHI"
);

SELECT SUM(SALARY) FROM EMPLOYEES
WHERE CITY = "DELHI";